# Generated by Django 3.1 on 2020-08-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('image', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('link_text', models.CharField(max_length=1000)),
                ('order', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
    ]
