# Generated by Django 3.1 on 2020-08-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='name',
            field=models.CharField(default='Message1', max_length=1000),
        ),
    ]
