# Generated by Django 3.1 on 2020-08-27 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0002_messages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='name',
            field=models.CharField(default='Message1', max_length=1000, unique=True),
        ),
        migrations.CreateModel(
            name='AfterRegistration',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagebot.messages', to_field='name')),
            ],
            options={
                'db_table': 'AfterRegistration',
            },
        ),
    ]
