# Generated by Django 3.1 on 2020-08-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0003_auto_20200827_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afterregistration',
            options={'verbose_name': 'After Registration'},
        ),
        migrations.CreateModel(
            name='SpecificDay',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagebot.messages', to_field='name')),
            ],
            options={
                'verbose_name': 'SpecificDay',
                'db_table': 'SpecificDay',
            },
        ),
        migrations.CreateModel(
            name='EveryDay',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagebot.messages', to_field='name')),
            ],
            options={
                'verbose_name': 'EveryDay',
                'db_table': 'EveryDay',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_date', models.DateTimeField()),
                ('time', models.DecimalField(decimal_places=15, max_digits=35)),
                ('user', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagebot.messages', to_field='name')),
            ],
            options={
                'verbose_name': 'Events',
                'db_table': 'Events',
            },
        ),
    ]
