# Generated by Django 3.1 on 2020-08-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0004_auto_20200827_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event'},
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.DecimalField(decimal_places=0, max_digits=35),
        ),
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.CharField(default='All', max_length=100),
        ),
    ]
