# Generated by Django 3.1 on 2020-08-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0006_auto_20200828_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.IntegerField(),
        ),
    ]
