# Generated by Django 3.1 on 2020-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0007_auto_20200828_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.CharField(default='ALL', max_length=100),
        ),
    ]
