# Generated by Django 3.1 on 2020-08-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0008_auto_20200828_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='link_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
