# Generated by Django 3.1 on 2020-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebot', '0009_auto_20200831_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='link',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='link_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
